"""empty message

Revision ID: bbf514f60141
Revises: 
Create Date: 2024-02-26 23:19:19.560460

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bbf514f60141'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alphabet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('letter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codepoint', sa.Integer(), nullable=False),
    sa.Column('symbol', postgresql.BYTEA(), nullable=True),
    sa.Column('custom', sa.Boolean(), nullable=True),
    sa.Column('red', sa.Integer(), nullable=False),
    sa.Column('green', sa.Integer(), nullable=False),
    sa.Column('blue', sa.Integer(), nullable=False),
    sa.Column('alphabet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alphabet_id'], ['alphabet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('letter')
    op.drop_table('alphabet')
    # ### end Alembic commands ###
